[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
anchor = "34ZvY6k6iKFRYhcimjjr57hzc31u5vK9GbfPimSBg9W9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://devnet.helius-rpc.com/?api-key=cb66f916-756c-4ee8-91d2-785d8a08d989"
# cluster = "localnet"
wallet = "./turbine-wallet.json"


[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
# test="yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/release_funds.ts"
